package leetcode;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 */

public class Find_the_Difference {

	public static void main(String[] args) {

		String s = "abcde";
		String t = "abcsde";

		System.out.println(findTheDifference(s, t));

	}
	
	/**
	 * 
	 * We all know that all the characters in s must appear in s and in t.
	 * As long as we wipe these characters away, we can get the only one different character.
	 * Here we also use XOR to turn the same character into zero. 
	 * 
	 */
	
	private static char findTheDifference(String s, String t) {

		char temp = 0x00;

		for (int i = 0; i < s.length(); i++) {
			temp = (char) (temp ^ s.charAt(i));
		}

		for (int i = 0; i < t.length(); i++) {
			temp = (char) (temp ^ t.charAt(i));
		}

		return temp;

	}

}
